var DraftConstants = {
  NEW_DRAFT: "NEW_DRAFT",
  GET_DRAFTS:  "GET_DRAFTS",
  UPDATE_EMAIL: "UPDATE_EMAIL",
  TOGGLE_SHOW: "TOGGLE_SHOW",
  CLOSE: "CLOSE",
  UPDATE_ALL: "UPDATE_ALL",
  DESTROY_DRAFT: "DESTROY_DRAFT",
  CLOSE_DRAFT: "CLOSE_DRAFT"
};

module.exports = DraftConstants;
