var EmailConstants = {
  GET_ALL_EMAIL: "GET_ALL_EMAIL",
  GET_EMAIL: "GET_EMAIL",
  CREATE_EMAIL: "CREATE_EMAIL",
  DELETE_EMAIL: "DELETE_EMAIL",
  UPDATE_EMAIL: "UPDATE_EMAIL",
  COMPOSE_EMAIL: "COMPOSE_EMAIL",
  CREATE_VIEW: "CREATE_VIEW"
};

module.exports = EmailConstants;
