var EmailConstants = {
  GET_ALL_EMAIL: "GET_ALL_EMAIL",
  GET_EMAIL: "GET_EMAIL",
  CREATE_EMAIL: "CREATE_EMAIL",
  DELETE_EMAIL: "DELETE_EMAIL",
  UPDATE_EMAIL: "UPDATE_EMAIL"
};

module.exports = EmailConstants;
