var SelectConstants = {
  TOGGLE_SELECT: "TOGGLE_SELECT",
  SELECT_ALL_READ: "SELECT_ALL_READ",
  SELECT_ALL_UNREAD: "SELECT_ALL_UNREAD",
  SELECT_ALL: "SELECT_ALL",
  SELECT_NONE: "SELECT_NONE"
};

module.exports = SelectConstants;
